apiVersion: v1
kind: Pod
metadata:
  name: eval
spec:
  restartPolicy: OnFailure
  containers:
    - name: eval
      image: "gcr.io/seventh-oven-198801/eval-gpu"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
